
apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    component: elasticsearch
    role: client
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    nodePort: 32000
    protocol: TCP
