---
# manage AWS environment
- hosts: localhost
  connection: local
  become: false
  vars_files:
    - vars/main.yaml
  environment:
    CLUSTER_NAME: "{{ route53.record.subDNS }}.{{ route53.zone.DNS }}"

  pre_tasks:
    - name: "Check if --tags is provided"
      fail:
        msg: "You must supply one(!) of the following tags: [create, aws-create, kops-create, deployment]"
      when: tags is not defined

  roles:
    - role: aws
    - role: kops
