---
# manage AWS environment
- hosts: localhost
  connection: local
  become: false
  vars_files:
    - vars/main.yaml

  pre_tasks:
    - name: "Check if --tags is provided"
      fail:
        msg: "You must supply one(!) of the following tags: [destroy, aws-destroy, kops-destroy]"
      when: tags is not defined

    - include: roles/aws/tasks/mng_ec2_keys/create.yaml
      vars:
        ec2_region: "{{ region }}"
        key_name: "{{ ec2_key_name }}"
      tags:
        - always

  roles:
    - role: kops
    - role: aws

  post_tasks:
    - include: roles/aws/tasks/mng_ec2_keys/delete.yaml
      vars:
        ec2_region: "{{ region }}"
        key_name: "{{ ec2_key_name }}"
      tags:
        - always
