---
# manage AWS environment
- hosts: localhost
  connection: local
  become: false
  vars_files:
    - vars/main.yaml

  vars:
    reverse_order: False

  pre_tasks:
    - name: "Check if --tags is provided"
      fail:
        msg: "You must supply one(!) of the following tags: [create, destroy, aws-create, aws-destroy, kops-create, kops-destroy]"
      when: tags is not defined

    - name: "Reverse the order of roles if in 'destroy' mode"
      set_fact: reverse_order=True
      tags: destroy

    - include: mng_ec2_keys/create.yaml
      vars:
        ec2_region: "{{ region }}"
        key_name: "{{ ec2_key_name }}"

  roles:
    - role: kops
      when: reverse_order == True
    - role: aws
    - role: kops
    - role: k8s
      when: reverse_order == False

  post_tasks:
    - include: mng_ec2_keys/delete.yaml
      vars:
        ec2_region: "{{ region }}"
        key_name: "{{ ec2_key_name }}"
