---
#Playbook for creating kops client localy
- hosts: localhost
  connection: local
  vars_files:
    - vars/configurations.yaml

  tasks:
    - name: create temp folder
      shell: mkdir "{{ temp_dir }}"

    - name: download kubectl
      get_url:
        url: "{{ urls.kubectl.url }}"
        dest: "/usr/local/bin/{{ urls.kubectl.pkg_name }}"
        mode: u+x

    - name: download kops
      get_url:
        url: "{{ urls.kops.url }}"
        dest: "/usr/local/bin/{{ urls.kops.pkg_name }}"
        mode: u+x

  roles:
    - role: update_packages

    - role: install_package_from_array
      apts_array: "{{ apts }}"

    # - role: wget_from_array
    #   urls_array: "{{ urls }}"

  handlers:
    - name: "Packages updated"
      shell: echo "Packages updated"

    - name: "{{ item }} Installed"
      shell: echo "{{ item }} Installed"
      with_items: "{{ apts }}"

    # - name: "{{ urls.kubectl.pkg_name }} downloaded"
    #   shell: sudo mv "{{ urls.kubectl.pkg_name }}" /usr/local/bin/"{{ urls.kubectl.pkg_name }}"
