---
#Playbook for creating kops client localy
- hosts: localhost
  connection: local
  become: true
  vars_files:
    - vars/configurations.yaml

  roles:
    - role: wget_if_not_downloaded
      file_name: "{{ urls.kubectl.pkg_name }}"
      file_url: "{{ urls.kubectl.urls }}"
      dest_folder: "{{ download_dir }}{{urls.kubectl.pkg_name}}"

    - role: wget_if_not_downloaded
      file_name: "{{ urls.kops.pkg_name }}"
      file_url: "{{ urls.kops.urls }}"
      dest_folder: "{{ download_dir }}{{urls.kops.pkg_name}}"

    - role: update_packages

    - role: install_package_from_array
      apts_array: "{{ apts }}"

  # handlers:
  #   - name: "Packages updated"
  #     shell: echo "Packages updated"
  #
  #   - name: "{{ item }} Installed"
  #     shell: echo "{{ item }} Installed"
  #     with_items: "{{ apts }}"

    # - name: "{{ urls.kubectl.pkg_name }} downloaded"
    #   shell: sudo mv "{{ urls.kubectl.pkg_name }}" /usr/local/bin/"{{ urls.kubectl.pkg_name }}"
