- hosts: localhost
  connection: local
  become: false
  gather_facts: false

  tasks:
    - name: "Publish run results to slack"
      slack:
        username: ansible-bot
        token: 
        msg: "{{ logfile }}"
      vars:
        logfile: "{{ lookup('file', './ansible.log') }}"
