---
- include: roles/aws/tasks/get_availability_zone/main.yaml
  vars:
    ec2_region: "{{ region }}"

- name: "Build cluster configuration in zone {{ aws_avail_zone }}"
  command: "kops create cluster {{ route53.record.subDNS }}.{{ route53.zone.DNS }} \
                                --cloud=aws \
                                --ssh-public-key=keys/{{ region }}/{{ ec2_key_name }}.pub \
                                --node-count={{ cluster.num_of_nodes }} \
                                --zones={{ aws_avail_zone }} \
                                --master-zones={{ aws_avail_zone }} \
                                --node-size={{ cluster.ec2_node_type }} \
                                --master-size={{ cluster.ec2_node_type }} \
                                --state=s3://{{ s3.bucket }}"
  ignore_errors: yes
