---
- name: "Remove SSH key from known hosts"
  command: "ssh-keygen -R api.{{ route53.record.subDNS }}.{{ route53.zone.DNS }}"

- name: "Destroy the cluster in AWS"
  command: "kops delete cluster --yes {{ route53.record.subDNS }}.{{ route53.zone.DNS }} --state=s3://{{ s3.bucket }}"
