---
# tasks file for kops
- include: roles/aws/tasks/mng_ec2_keys/fetch-if-not-available.yaml

- include: create_cluster.yaml
  tags:
    - create
    - kops-create

- include: apply_cluster_creation.yaml
  tags:
    - create
    - kops-create

- include: delete_cluster.yaml
  tags:
    - destroy
    - kops-destroy
