---
- name: "Deploy {{ item.deployment_name }} to cluster"
  set_fact:
    deployment_file: temp/{{ route53.zone.DNS }}/deployments/{{ item.deployment_name }}-deployment.yaml
    service_file: "temp/{{ route53.zone.DNS }}/deployments/{{ item.deployment_name }}-service.yaml"

- name: "Create a deployment config file"
  template:
    src: k8s_deployment.yaml
    dest: "{{ deployment_file }}"

- name: "Create a service config file"
  template:
    src: k8s_service.yaml
    dest: "{{ service_file }}"
  vars:
    identifier: service
  when: item.expose is undefined or item.expose == False

- name: "Create an external service config file"
  template:
    src: k8s_service.yaml
    dest: "{{ service_file }}"
  vars:
    lb_type: LoadBalancer
    identifier: ext-service
    is_external: True
  when: item.expose is defined and item.expose != False

- block:
    - name: "Create a new k8s Deployment for {{ item.deployment_name }}"
      command: "kubectl create -f {{ deployment_file }} --record"
  rescue:
    - name: "Delete old deployment"
      command: "kubectl delete -f {{ deployment_file }}"
    - name: "Try to deploy again"
      command: "kubectl create -f {{ deployment_file }} --record"

- block:
    - name: "Create a new k8s Service for {{ item.deployment_name }}"
      command: "kubectl create -f {{ service_file }} --record"
  rescue:
    - name: "Delete old service"
      command: "kubectl delete -f {{ service_file }}"
    - name: "Try to deploy service again"
      command: "kubectl create -f {{ service_file }} --record"
