---
- name: "Get load balancer DNS name"
  command: "kubectl get services -o jsonpath='{.items[?(@.metadata.name==\"{{ service_name }}\")].status.loadBalancer.ingress[?(@.hostname)].hostname}'"
  register: service_url_output

- set_fact:
    service_url: "{{ service_url_output.stdout }}"

- name: "Print url {{ service_url }}"
  debug:
    msg: "{{ service_url }}"
