---
- include: k8s_configmap_task.yaml
  vars:
    configmap_name: "{{ cluster.configmap_name }}"
    configmap_path: "/home/admin/vars/configmaps"
  tags:
    - deployments

- include: k8s_secret_task.yaml
  vars:
    secret_name: "{{ cluster.secret_name }}"
    secret_path: "/home/admin/vars/secrets"
  tags:
    - deployments

- include: k8s_deployment_task.yaml
  vars:
    deployments_path: "/home/admin/vars/deployments"
  tags:
    - deployments
