---
# vars file for k8s
deployments:
  - deployment_name: private-registry
    namespace: kube-system
    num_of_replicas: 1
    labels:
      - key: k8s-app
        value: private-registry
      - key: environment
        value: dev
    volumes:
      name: image-store
      type: emptyDir
      value: {}
    containers:
      - container_name: private-registry
        deployment_image: registry
        deployment_tag: 2
        ports:
          - port: 5000
        env_vars:
          - name: REGISTRY_HTTP_ADDR
            value: :5000
          - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
            value: /var/lib/registry
        volume_mounts:
          - name: image-store
            path: /var/lib/registry
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
  - deployment_name: hello-world
    namespace: default
    num_of_replicas: 1
    labels:
      - key: k8s-app
        value: hello-world
      - key: environment
        value: dev
    containers:
      - container_name: hello-world
        deployment_image: vayuadm/ceribro
        deployment_tag: latest
        ports:
          - port: 80
            targetPort: 8090
        # env_vars:
        #   - name:
        #     value:
    expose:
      # DNS:
      subDNS: hello-world
