apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      containers:
      - name: kibana
        image: kibana
        env:
        - name: ELASTICSEARCH_URL
          value: "http://es:9200"
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
