---
kind: Service
apiVersion: v1
metadata:
  name: kube-distribution-service
  labels:
    component: kube-distribution
    kubernetes.io/cluster-service: "true"
spec:
  type: LoadBalancer
  selector:
    app: kube-distribution
  ports:
    - name: http
      port: 5050
      targetPort: 5050
      protocol: TCP
