---
- include: k8s_deployment_task.yaml
  vars:
    deployments_path: "/home/admin/vars/poc"
  tags:
    - deployments

- include: create_alias_for_elb_task.yaml
  vars:
    service: "kube-distribution-service"
    alias_name: "{{ route53.alias.record.distributor_name }}.{{ route53.zone.DNS }}"
  tags:
    - deployments

- include: create_alias_for_elb_task.yaml
  vars:
    service: "poc-service"
    alias_name: "{{ route53.alias.record.app_name }}.{{ route53.zone.DNS }}"
  tags:
    - deployments
