---
- include: k8s_deployment_task.yaml
  vars:
    deployments_path: "/home/admin/vars/poc"
  tags:
    - deployments

- include: roles/k8s/tasks/k8s_get_loadbalancer_ext_url.yaml
  vars:
    service_name: "kube-distribution-service"
  tags:
    - deployments

# Gather facts about all ELBs
- action:
    module: ec2_elb_facts
  register: elb_facts

- name: Get poc load balancer
  shell: "echo {{ item }}"
  register: "elb"
  with_items: elb_facts.elbs
  when: item.dns_name == service_url

- debug: var=elb

- include: roles/aws/tasks/mng_route53/register/create-alias.yaml
  vars:
    zone_name: "{{ route53.zone.DNS }}"
    elb_alias_name: "{{ route53.alias.record.mame }}.{{ route53.zone.DNS }}"
    record_type: "{{ route53.alias.record.type }}"
    elb_dns_name: "{{ service_url }}"
