---
- include: k8s_deployment_task.yaml
  vars:
    deployments_path: "/home/admin/vars/poc"
  tags:
    - deployments

- include: roles/k8s/tasks/k8s_get_loadbalancer_ext_url.yaml
  vars:
    service_name: "kube-distribution-service"
  tags:
    - deployments

- action:
    module: ec2_elb_facts
  register: elb_facts
  tags:
    - deployments
    
- action:
    module: debug
    msg: "{{ item }}"
  with_items: "{{ elb_facts.elbs }}"
  when: item.dns_name == service_url
  tags:
    - deployments

- include: roles/aws/tasks/mng_route53/register/create-alias.yaml
  vars:
    zone_name: "{{ route53.zone.DNS }}"
    elb_alias_name: "{{ route53.alias.record.name }}.{{ route53.zone.DNS }}"
    record_type: "{{ route53.alias.record.type }}"
    elb_dns_name: "{{ service_url }}"
  when: service_url is defined and service_url != ""
  tags:
    - deployments
