---
- include: mng_ec2_keys/create.yaml
  vars:
    ec2_region: "{{ region }}"
    key_name: "{{ ec2_key_name }}"

- include: mng_route53/zone/create.yaml
  vars:
    zone_name: "{{ route53.zone.DNS }}"
    zone_comment: "{{ route53.zone.comment }}"

- include: mng_route53/register/create.yaml
  vars:
    zone_name: "{{ route53.zone.DNS }}"
    record_name: "{{ route53.record.subDNS }}.{{ route53.zone.DNS }}"
    record_type: "{{ route53.record.type }}"
    record_value: "{{ route53.record.value }}"

- include: mng_s3_bucket/create.yaml
  vars:
    bucket_name: "{{ s3.bucket }}"
    bucket_region: "{{ region }}"
