---

- name: "Destroy the cluster in AWS"
  shell: "kops delete cluster --yes --state=s3://{{ s3.bucket }} {{ route53.record.subDNS }}.{{ route53.zone.DNS }}"

- include: mng_ec2_keys.yaml
  vars:
    action: "destroy"

- include: mng_s3_bucket.yaml
  vars:
    action: "destroy"
    bucket_name: "{{ s3.bucket }}"
    bucket_region: "{{ region }}"

- include: mng_dns_register.yaml
  vars:
    action: "destroy"
    zone_name: "{{ route53.zone.DNS }}"
    record_name: "{{ route53.record.subDNS }}.{{ route53.zone.DNS }}"
    record_type: "{{ route53.record.type }}"
    record_value: "{{ route53.record.value }}"

- include: mng_dns_zone.yaml
  vars:
    action: "destroy"
    zone_name: "{{ route53.zone.DNS }}"
