---

- name: "Create a DNS zone"
  route53_zone:
    zone: "{{ zone_name }}"
    state: present
    comment: "{{ zone_comment }}"
  when: action == "create"

- name: "Delete a DNS zone"
  route53_zone:
    state: absent
    zone: "{{ zone_name }}"
  when: action == "destroy"
