apiVersion: v1
kind: Service
metadata:
   name: kibana
   labels:
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: "kibana"
spec:
  type: NodePort
  selector:
    component: elk
    role: kibana
  ports:
  - name: http
    port: 5601
    nodePort: 31000
    protocol: TCP
