---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  labels:
    component: nginx
    kubernetes.io/cluster-service: "true"
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      nodePort: 32200
      protocol: TCP
